[features]
seeds = false
skip-lint = false

[programs.devnet]
ikapayfi_policy_engine = "54Rek86pHBP5V6GM4MieoMSup1ueVtuS56Tqz9SQXetb"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node --test"
